config/routes.rb
Rails.application.routes.draw do
  resources :static_pages

  root to: 'static_pages#index'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JSPlay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<style type="text/css">
  canvas {
    border: 1px solid black;
  }
</style>
<h1>Breakout</h1>

<canvas id="canvas" width="400" height="500">
  Your browser does not support the HTML5 Canvs feature. This game uses new HTML5 features and will only work with the latest versions of the popular browsers.
</canvas>

<script type="text/javascript">

var canvas = $('canvas')[0];
var context = canvas.getContext('2d');

var paddleX = 200;
var paddleY = 460;

var paddleWidth = 100;
var paddleHeight = 15;

var paddleDeltaX = 0; 
var paddleDeltaY = 0; 

function drawPaddle(){
  context.fillRect(paddleX,paddleY,paddleWidth,paddleHeight);
}

var ballX = 300;
var ballY = 300;
var ballRadius = 10;

function drawBall(){
  context.beginPath();

  context.arc(ballX,ballY,ballRadius,0,Math.PI*2,true);

  context.fill();
}

var bricksPerRow = 8;
var brickHeight = 20;
var brickWidth = canvas.width/bricksPerRow;

var bricks = [
  [1,1,1,1,1,1,1,2],
  [1,1,3,1,0,1,1,1],
  [2,1,2,1,2,1,0,1],
  [1,2,1,1,0,3,1,1]
];

function createBricks(){
  for (var i=0; i < bricks.length; i++) {
    for (var j=0; j < bricks[i].length; j++) {
      drawBrick(j,i,bricks[i][j]);
    }
  }
}

function drawBrick(x,y,type){
  switch(type){
    case 1:
      context.fillStyle = 'orange';
      break;
    case 2:
      context.fillStyle = 'rgba(100,200,100)';
      break;
    case 3:
      context.fillStyle = 'rgba(50,100,50,.5)';
      break;
    default:
      context.clearRect(x*brickWidth,y*brickHeight,brickWidth,brickHeight);
      break;

  }
  if (type){
    context.fillRect(x*brickWidth,y*brickHeight,brickWidth,brickHeight);
    context.strokeRect(x*brickWidth+1,y*brickHeight+1,brickWidth-2,brickHeight-2);
  }
}

var score = 0;

function displayScoreBoard(){
  context.fillStyle = 'rgb(50,100,50)';
  context.font = '20px Times New Roman';

  context.clearRect(0,canvas.height-30,canvas.width,30);
  context.fillText('Score: '+score,10,canvas.height-5);

}



function startGame(){
  ballDeltaY = -2;
  ballDeltaX = -4;
  paddleMove = 'NONE';
  paddleDeltaX = 0;

  gameLoop = setInterval(animate,20);

  $(document).keydown(function(evt){
    if (evt.keyCode == 39){
      paddleMove = 'RIGHT';
    }else if (evt.keyCode == 37){
      paddleMove = 'LEFT';
    }
  });

  $(document).keyup(function(evt){
    if (evt.keyCode == 39){
      paddleMove = 'NONE';
    } else if (evt.keyCode == 37){
      paddleMove = 'NONE';
    }
  });
}

function endGame(){
  clearInterval(gameLoop);
  context.fillText('The End!!!',canvas.width/2,canvas.height/2);
}

startGame();


var ballDeltaX;
var ballDeltaY;

function moveBall(){

  if (ballY + ballDeltaY + ballRadius >= paddleY){
    if (ballX + ballDeltaX <= paddleX + paddleWidth){
      ballDeltaY = -ballDeltaY;
    }
  }

  if (ballY + ballDeltaY - ballRadius < 0){
    ballDeltaY = -ballDeltaY;
  }

  if (ballY + ballDeltaY + ballRadius > canvas.height){
    endGame();
  }

  if ((ballX + ballDeltaX -ballRadius < 0) ||
      (ballX + ballDeltaX + ballRadius > canvas.width)){
    ballDeltaX = -ballDeltaX;
  }

  ballX = ballX + ballDeltaX;
  ballY = ballY + ballDeltaY;
}

var paddleDeltax;
var paddleSpeedX = 10;

function movePaddle(){
  if (paddleMove == 'LEFT'){
    paddleDeltaX = -paddleSpeedX;
  } else if (paddleMove == 'RIGHT'){
    paddleDeltaX = paddleSpeedX;
  } else {
    paddleDeltaX = 0;
  }

  if (paddleX + paddleDeltaX < 0 || paddleX + paddleDeltaX +paddleWidth > canvas.width){
    paddleDeltaX = 0;
  }
  paddleX = paddleX + paddleDeltaX;
}


function animate(){
  context.clearRect(0,0,canvas.width,canvas.height);
  moveBall();
  movePaddle();
  drawPaddle();
  drawBall();
}




</script>

<script type="text/javascript">

drawPaddle();
drawBall();
createBricks();
displayScoreBoard();

</script>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>